### ISSUE TITLE
cut new maven central release

### ISSUE THREAD

**Issue by timit** [logiclander/jaasmine#1]
several changes have been made to sonatype requirements since our last release to maven central.  please review these requirements and revise and jaasmine code, configuration, and documentation appropriately.

http://central.sonatype.org/pages/apache-maven.html

**Comment by argherna** [comment]
[Deja vu. Felt like I've been working on this...]

**Comment by timit** [comment]
i was finally able to get jaasmine-core staged (https://oss.sonatype.org/#stagingRepositories) by running `mvn -Prelease clean install deploy` from the `jaasmine-core` directory of the latest tagged release `jaasmine-1.2.1`.

**Comment by timit** [comment]
[yeah... i figured we better capture some of this learning for future reference as necessary]

**Comment by argherna** [comment]
So is 1.2.1 deployed? I'm confused. And if it is, then what is the purpose of this issue?

**Comment by timit** [comment]
great. we inspected the artifact in the staging area (finally!), and then ran `mvn nexus-staging:release` from the `jaasmine-core` directory of the latest tagged release `jaasmine-1.2.1`.  this transitioned the library from the staging repository to maven central... woohoo!

**Comment by timit** [comment]
andy confirmed!
